#!/bin/sh

# update the list of modules for modprobe
depmod

# load the module
modprobe raspicommrs485

# add the module to /etc/modules so that it gets loaded on system startup
echo "raspicommrs485" >> /etc/modules